In [37]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.gaussian_process import GaussianProcessRegressor

In [38]:
X = np.load('initial_inputs.npy')
Y = np.load('initial_outputs.npy')

In [39]:
# Week 1
X = np.append(X, np.array([[0.999999, 0.999999, 0.999999]]), axis=0)
Y = np.append(Y, -0.196020925114507)

In [40]:
# Week 2
X = np.append(X, np.array([[0.999999, 0.0, 0.70707]]), axis=0)
Y = np.append(Y, -0.4949776013)

In [41]:
# Week 3, submission for M15, submitted on Mon Hune 2024
X = np.append(X, np.array([[0.474747, 0.999999, 0.000000]]), axis=0)
Y = np.append(Y, -0.156923158387769)

In [42]:
print('X : ',  X)
print('Y : ', Y)

X :  [[0.17152521 0.34391687 0.2487372 ]
 [0.24211446 0.64407427 0.27243281]
 [0.53490572 0.39850092 0.17338873]
 [0.49258141 0.61159319 0.34017639]
 [0.13462167 0.21991724 0.45820622]
 [0.34552327 0.94135983 0.26936348]
 [0.15183663 0.43999062 0.99088187]
 [0.64550284 0.39714294 0.91977134]
 [0.74691195 0.28419631 0.22629985]
 [0.17047699 0.6970324  0.14916943]
 [0.22054934 0.29782524 0.34355534]
 [0.66601366 0.67198515 0.2462953 ]
 [0.04680895 0.23136024 0.77061759]
 [0.60009728 0.72513573 0.06608864]
 [0.96599485 0.86111969 0.56682913]
 [0.999999   0.999999   0.999999  ]
 [0.999999   0.         0.70707   ]
 [0.474747   0.999999   0.        ]]
Y :  [-0.1121222  -0.08796286 -0.11141465 -0.03483531 -0.04800758 -0.11062091
 -0.39892551 -0.11386851 -0.13146061 -0.09418956 -0.04694741 -0.10596504
 -0.11804826 -0.03637783 -0.05675837 -0.19602093 -0.4949776  -0.15692316]


In [43]:
import itertools as it

In [44]:
dim = 3
X_grid = np.fromiter(it.chain(*it.product(np.linspace(0, 1, 100), repeat=dim)), dtype=float).reshape(-1,dim)

In [45]:
def upper_confidance_bound(i_param, o_param):
    gpr = GaussianProcessRegressor()
    gpr.fit(i_param, o_param)
    mean, std = gpr.predict(X_grid, return_std = True)
    ucb = mean + 1 * std
    return ucb


In [46]:
def get_next(upper_conf):
    idx_max = np.argmax(upper_conf)
    next_query = X_grid[idx_max]
    return next_query

In [47]:
ucb = upper_confidance_bound(X,Y)

In [48]:
print(get_next(upper_conf=ucb))

[1. 0. 0.]
