In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.gaussian_process import GaussianProcessRegressor

In [14]:
X = np.load('initial_inputs.npy')
Y = np.load('initial_outputs.npy')

In [15]:
# Week 1
X = np.append(X, np.array([[0.0, 0.0, 0.111111, 0.0, 0.222222, 0.999999]]), axis=0)
Y = np.append(Y, 0.341945960681604)

In [16]:
# Week 2
X = np.append(X, np.array([[0.999999, 0.999999, 0.222222, 0.999999, 0.999999, 0.000000]]), axis=0)
Y = np.append(Y, 0.001003495689)

In [17]:
# Week 3, submission for M15, submitted on Mon Hune 2024
X = np.append(X, np.array([[0.000000, 0.999999, 0.000000, 0.000000, 0.333333, 0.000000]]), axis=0)
Y = np.append(Y, 0.00815600414602021)

In [18]:
print('X : ',  X)
print('Y : ', Y)

X :  [[0.27262382 0.32449536 0.89710881 0.83295115 0.15406269 0.79586362]
 [0.54300258 0.9246939  0.34156746 0.64648585 0.71844033 0.34313266]
 [0.09083225 0.66152938 0.06593091 0.25857701 0.96345285 0.6402654 ]
 [0.11886697 0.61505494 0.90581639 0.8553003  0.41363143 0.58523563]
 [0.63021764 0.8380969  0.68001305 0.73189509 0.52673671 0.34842921]
 [0.76491917 0.25588292 0.60908422 0.21807904 0.32294277 0.09579366]
 [0.05789554 0.49167222 0.24742222 0.21811844 0.42042833 0.73096984]
 [0.19525188 0.07922665 0.55458046 0.17056682 0.01494418 0.10703171]
 [0.64230298 0.83687455 0.02179269 0.10148801 0.68307083 0.6924164 ]
 [0.78994255 0.19554501 0.57562333 0.07365919 0.25904917 0.05109986]
 [0.52849733 0.45742436 0.36009569 0.36204551 0.81689098 0.63747637]
 [0.72261522 0.01181284 0.06364591 0.16517311 0.07924415 0.35995166]
 [0.07566492 0.33450212 0.13273274 0.60831236 0.91838592 0.82233079]
 [0.94245084 0.37743962 0.48612233 0.22879108 0.08263175 0.71195755]
 [0.14864702 0.03394336 0.728

In [19]:
import itertools as it

In [20]:
dim = 6
X_grid = np.fromiter(it.chain(*it.product(np.linspace(0, 1, 10), repeat=dim)), dtype=float).reshape(-1,dim)

In [21]:
def upper_confidance_bound(i_param, o_param):
    gpr = GaussianProcessRegressor()
    gpr.fit(i_param, o_param)
    mean, std = gpr.predict(X_grid, return_std = True)
    ucb = mean + 1.2 * std
    return ucb


In [22]:
def get_next(upper_conf):
    idx_max = np.argmax(upper_conf)
    next_query = X_grid[idx_max]
    return next_query

In [23]:
ucb = upper_confidance_bound(X,Y)

In [24]:
print(get_next(upper_conf=ucb))

[0.         0.66666667 0.66666667 0.         0.33333333 1.        ]
