In [25]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.gaussian_process import GaussianProcessRegressor

In [26]:
X = np.load('initial_inputs.npy')
Y = np.load('initial_outputs.npy')

In [27]:
# Week 1
X = np.append(X, np.array([[0.0, 0.052631, 0.052631, 0.999999, 0.0]]), axis=0)
Y = np.append(Y, -1.67008589427023)

In [28]:
# Week 2
X = np.append(X, np.array([[0.315789, 0.000000, 0.999999, 0.999999, 0.157895]]), axis=0)
Y = np.append(Y, -1.062149105)

In [29]:
# Week 3, submission for M15, submitted on Mon Hune 2024
X = np.append(X, np.array([[0.263158, 0.999999, 0.000000, 0.999999, 0.000000     ]]), axis=0)
Y = np.append(Y, -1.81124887980155)

In [30]:
print('X : ',  X)
print('Y : ', Y)

X :  [[0.7281861  0.15469257 0.73255167 0.69399651 0.05640131]
 [0.24238435 0.84409997 0.5778091  0.67902128 0.50195289]
 [0.72952261 0.7481062  0.67977464 0.35655228 0.67105368]
 [0.77062024 0.11440374 0.04677993 0.64832428 0.27354905]
 [0.6188123  0.33180214 0.18728787 0.75623847 0.3288348 ]
 [0.78495809 0.91068235 0.7081201  0.95922543 0.0049115 ]
 [0.14511079 0.8966846  0.89632223 0.72627154 0.23627199]
 [0.94506907 0.28845905 0.97880576 0.96165559 0.59801594]
 [0.12572016 0.86272469 0.02854433 0.24660527 0.75120624]
 [0.75759436 0.35583141 0.0165229  0.4342072  0.11243304]
 [0.5367969  0.30878091 0.41187929 0.38822518 0.5225283 ]
 [0.95773967 0.23566857 0.09914585 0.15680593 0.07131737]
 [0.6293079  0.80348368 0.81140844 0.04561319 0.11062446]
 [0.02173531 0.42808424 0.83593944 0.48948866 0.51108173]
 [0.43934426 0.69892383 0.42682022 0.10947609 0.87788847]
 [0.25890557 0.79367771 0.6421139  0.19667346 0.59310318]
 [0.43216593 0.71561781 0.3418191  0.70499988 0.61496184]
 [0.78287

In [31]:
import itertools as it

In [32]:
dim = 5
X_grid = np.fromiter(it.chain(*it.product(np.linspace(0, 1, 20), repeat=dim)), dtype=float).reshape(-1,dim)

In [33]:
def upper_confidance_bound(i_param, o_param):
    gpr = GaussianProcessRegressor()
    gpr.fit(i_param, o_param)
    mean, std = gpr.predict(X_grid, return_std = True)
    ucb = mean + 1.5 * std
    return ucb


In [34]:
def get_next(upper_conf):
    idx_max = np.argmax(upper_conf)
    next_query = X_grid[idx_max]
    return next_query

In [35]:
ucb = upper_confidance_bound(X,Y)

In [36]:
print(get_next(upper_conf=ucb))

[0.42105263 0.31578947 0.52631579 0.73684211 0.10526316]
