In [37]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.gaussian_process import GaussianProcessRegressor

In [38]:
X = np.load('initial_inputs.npy')
Y = np.load('initial_outputs.npy')

In [39]:
# Week 1
X = np.append(X, np.array([[0.666666, 0.999999, 0.999999, 0.999999]]), axis=0)
Y = np.append(Y, 5188.01687646763)

In [40]:
# Week 2
X = np.append(X, np.array([[0.999999, 0.999999, 0.999999, 0.999999]]), axis=0)
Y = np.append(Y, 8662.405001)

In [41]:
# Week 3, submission for M15, submitted on Mon Hune 2024
X = np.append(X, np.array([[0.999999, 0.999999, 0.999999, 0.999999]]), axis=0)
Y = np.append(Y, 8662.4050012483)

In [42]:
print('X : ',  X)
print('Y : ', Y)

X :  [[0.19144708 0.03819337 0.60741781 0.41458414]
 [0.75865295 0.53651774 0.65600038 0.36034155]
 [0.43834987 0.8043397  0.21024527 0.15129482]
 [0.70605083 0.53419196 0.26424335 0.48208755]
 [0.83647799 0.19360965 0.6638927  0.78564888]
 [0.68343225 0.11866264 0.82904591 0.56757661]
 [0.55362148 0.66734998 0.32380582 0.81486975]
 [0.35235627 0.32224153 0.11697937 0.47311252]
 [0.15378571 0.72938169 0.42259844 0.44307417]
 [0.46344227 0.63002451 0.10790646 0.9576439 ]
 [0.67749115 0.35850951 0.47959222 0.07288048]
 [0.58397341 0.14724265 0.34809746 0.42861465]
 [0.30688872 0.31687813 0.62263448 0.09539906]
 [0.51114177 0.817957   0.72871042 0.11235362]
 [0.43893338 0.77409176 0.37816709 0.93369621]
 [0.22418902 0.84648049 0.87948418 0.87851568]
 [0.72526172 0.47987049 0.08894684 0.75976022]
 [0.35548161 0.63961937 0.41761768 0.12260384]
 [0.11987923 0.86254031 0.64333133 0.84980383]
 [0.12688467 0.15342962 0.77016219 0.19051811]
 [0.666666   0.999999   0.999999   0.999999  ]
 [0.9999

In [43]:
import itertools as it

In [44]:
dim = 4
X_grid = np.fromiter(it.chain(*it.product(np.linspace(0, 1, 25), repeat=dim)), dtype=float).reshape(-1,dim)

In [45]:
def upper_confidance_bound(i_param, o_param):
    gpr = GaussianProcessRegressor()
    gpr.fit(i_param, o_param)
    mean, std = gpr.predict(X_grid, return_std = True)
    ucb = mean + 1.96 * std
    return ucb


In [46]:
def get_next(upper_conf):
    idx_max = np.argmax(upper_conf)
    next_query = X_grid[idx_max]
    return next_query

In [47]:
ucb = upper_confidance_bound(X,Y)

In [48]:
print(get_next(upper_conf=ucb))

[1. 1. 1. 1.]
