In [34]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.gaussian_process import GaussianProcessRegressor

In [35]:
X = np.load('initial_inputs.npy')
Y = np.load('initial_outputs.npy')

In [36]:
# Week 1
X = np.append(X, np.array([[0.416667, 0.375, 0.333333, 0.458333]]), axis=0)
Y = np.append(Y, -0.3843606398)

In [37]:
# Week 3, submission for M15, submitted on Mon Hune 2024
X = np.append(X, np.array([[0.416667, 0.375000, 0.333333, 0.416667]]), axis=0)
Y = np.append(Y, 0.330240283465102)

In [38]:
print('X : ',  X)
print('Y : ', Y)

X :  [[0.89698105 0.72562797 0.17540431 0.70169437]
 [0.8893564  0.49958786 0.53926886 0.50878344]
 [0.25094624 0.03369313 0.14538002 0.49493242]
 [0.34696206 0.0062504  0.76056361 0.61302356]
 [0.12487118 0.12977019 0.38440048 0.2870761 ]
 [0.80130271 0.50023109 0.70664456 0.19510284]
 [0.24770826 0.06044543 0.04218635 0.44132425]
 [0.74670224 0.7570915  0.36935306 0.20656628]
 [0.40066503 0.07257425 0.88676825 0.24384229]
 [0.6260706  0.58675126 0.43880578 0.77885769]
 [0.95713529 0.59764438 0.76611385 0.77620991]
 [0.73281243 0.14524998 0.47681272 0.13336573]
 [0.65511548 0.07239183 0.68715175 0.08151656]
 [0.21973443 0.83203134 0.48286416 0.08256923]
 [0.48859419 0.2119651  0.93917791 0.37619173]
 [0.16713049 0.87655456 0.21723954 0.95980098]
 [0.21691119 0.16608583 0.24137226 0.77006248]
 [0.38748784 0.80453226 0.75179548 0.72382744]
 [0.98562189 0.66693268 0.15678328 0.8565348 ]
 [0.03782483 0.66485335 0.16198218 0.25392378]
 [0.68348638 0.9027701  0.33541983 0.99948256]
 [0.1703

In [39]:
import itertools as it

In [40]:
dim = 4
X_grid = np.fromiter(it.chain(*it.product(np.linspace(0, 1, 25), repeat=dim)), dtype=float).reshape(-1,dim)

In [41]:
def upper_confidance_bound(i_param, o_param):
    gpr = GaussianProcessRegressor()
    gpr.fit(i_param, o_param)
    mean, std = gpr.predict(X_grid, return_std = True)
    ucb = mean + 1.85 * std
    return ucb


In [42]:
def get_next(upper_conf):
    idx_max = np.argmax(upper_conf)
    next_query = X_grid[idx_max]
    return next_query

In [43]:
ucb = upper_confidance_bound(X,Y)

In [44]:
print(get_next(upper_conf=ucb))

[0.45833333 0.45833333 0.         0.25      ]
